import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;


public class BasicExample {

	public static void main(String[] args) throws MalformedURLException, ClassNotFoundException, InstantiationException, IllegalAccessException, SecurityException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException {
		String strDistJar = "../dist/http-request-tag-engine-0.0.1-dist.jar";
		String strHttpRequestTagEngine = "HttpRequestTagEngine";

		File fileDistJar = new File(strDistJar);
		URL urlDistJar = fileDistJar.toURI().toURL();
		URLClassLoader classLoader = new URLClassLoader(new URL[]{ urlDistJar });
		Class<?> classHttpRequestTagEngine = classLoader.loadClass(strHttpRequestTagEngine);
		Object engine = classHttpRequestTagEngine.newInstance();
		Method methodSetDpi = classHttpRequestTagEngine.getMethod("setDpi", String.class);
		methodSetDpi.invoke(engine, "GW");
		Method methodLoadPlugin = classHttpRequestTagEngine.getMethod("loadPlugin", String.class);
		methodLoadPlugin.invoke(engine, "atom-id");
		Method methodTagging = classHttpRequestTagEngine.getMethod("tagging", String.class);
		methodTagging.invoke(engine, "b00423597|06|117.89.60.194|180.97.66.49|072f|0050|dDEwLmJhaWR1LmNvbQ==|aHR0cDovL3QxMC5iYWlkdS5jb20vaXQvdT03NjM5OTkyNTcsMTMzMDU1ODgyMSZmbT03Ng==|aHR0cDovL3Bvcy5iYWlkdS5jb20vYWNvbT9zej03MDh4NDMwJnJkaWQ9MjExNzI1MiZkYz0yJmRpPXUyMTE3MjUyJmRyaT0wJmRpcz03JmRhaT0xJnBzPS0yeC0yJmNvYT1hdCUzRDMlMjZyc2kwJTNENzA4JTI2cnNpMSUzRDQzMCUyNnBhdCUzRDYlMjZ0biUzRGJhaWR1Q3VzdE5hdGl2ZUFEJTI2cnNzMSUzRCUyNTIzRkZGRkZGJTI2Y29uQlclM0QwJTI2YWRwJTNEMSUyNnB0dCUzRDAlMjZ0aXRGRiUzRCUyNTI1RTUlMjUyNUJFJTI1MjVBRSUyNTI1RTglMjUyNUJEJTI1MjVBRiUyNTI1RTklMjUyNTlCJTI1MjU4NSUyNTI1RTklMjUyNUJCJTI1MjU5MSUyNnRpdEZTJTNEMTQlMjZyc3MyJTNEJTI1MjMwMDAwMDAlMjZ0aXRTVSUzRDAlMjZwdGJnJTNEOTAlMjZwaXclM0QxMzAlMjZwaWglM0Q4MCUyNnB0cCUzRDAmZGNiPUJBSURVX1VOSU9OX2RlZmluZSZkdG09QkFJRFVfRFVQX1NFVEpTT05BRFNMT1QmZHZpPTAuMCZkY2k9LTEmZHB0PW5vbmUmdHNyPTAmdHByPTE0NTU0MTI1MDAzNjgmdGk9JUU1JThEJTk1JUU1JUIxJThGJUU2JTk3JUEwJUU1JUI5JUJGJUU1JTkxJThBJmFyaT0xJmRidj0wJmRycz0zJnBjcz0weDAmcHNzPTB4MCZjZnY9MTkmY3BsPTAmY2hpPTAmY2NlPXRydWUmY2VjPXV0Zi04JnRsbT0xNDQ0MzgyMjA4Jmx0dT1odHRwJTNBJTJGJTJGaW1nMi5taW5pLmNhY2hlLndwcy5jbiUyRndwc21pbmliZCUyRndwc21pbmklMkZwYXJ0bmVyc193ZWIlMkZyZWNvbW1lbmQlMkYmbGl1PWh0dHAlM0ElMkYlMkZpbWcyLm1pbmkuY2FjaGUud3BzLmNuJTJGd3BzbWluaWJkJTJGd3BzbWluaSUyRnBhcnRuZXJzX3dlYiUyRnJlY29tbWVuZCUyRiZlY2Q9MCZwc3I9MTQ0MHg5MDAmcGFyPTE0NDB4ODY2JnBpcz0weDAmY2NkPTMyJmNqYT10cnVlJmNtaT0wJmNvbD16aC1jbiZjZG89LTEmdGNuPTE0NTU0MTI1MDEmcW49ZWM4MmVjOWNhMjMyOTk3NCZ0dD0xNDU1NDEyNTAwMjI4LjI5Ny4zMTIuMzEy|TW96aWxsYS80LjAgKGNvbXBhdGlibGU7IE1TSUUgNi4wOyBXaW5kb3dzIE5UIDUuMTsgU1YxOyAuTkVUIENMUiAyLjAuNTA3Mjcp|QkFJRFVJRD1CMTNDNTFGMkFDM0E3MzQ0MEYxRDk5QzMyREJBODFBRTpGRz0x|1455412500");

	}

}
